apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "powerdns-sqlite3.fullname" . }}-config
  labels:
    {{- include "powerdns-sqlite3.labels" . | nindent 4 }}
data:
  pdns.conf: |
    local-address=0.0.0.0
    local-port=53
    launch=gsqlite3
    gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
    api=yes
    api-key=${API_KEY}
    webserver=yes
    webserver-port=8081
    webserver-address=0.0.0.0

