apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-sqlite3.fullname" . }}-api-key
  labels:
    {{- include "powerdns-sqlite3.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: "{{ .Values.config.apiKey | b64enc }}"
